### PR TITLE
Updated the documentation for the Generate Documentation workflow.

### PR DESCRIPTION
**Pull request by gsrohde**
I updated and clarified this documentation and eliminated references to `ebimodeling` repositories.

### CODE REVIEW

**Comment by eloch216** [comment]
Looks good. My only critique is that all the items in the numbered list are number 1.

To check my `git-flow` understanding... the target for this PR is `develop` since it isn't critical for the operation of the R package or the workflows, whereas the target for PR #36 is `main` since it _is_ critical for the operation of the workflows?

**Comment by gsrohde** [comment]
> Looks good. My only critique is that all the items in the numbered list are number 1.
> 

This is the way Markdown handles numbered lists.  It spares one having to renumber everything if you add a new item in the middle.  They will be numbered correctly when they appear in the **bookdown** book.

> To check my `git-flow` understanding... the target for this PR is `develop` since it isn't critical for the operation of the R package or the workflows, whereas the target for PR #36 is `main` since it _is_ critical for the operation of the workflows?

Yes.  There will have to be many adjustments to the documentation in connection with changing locations from `ebimodeling/biocro` to `biocro/biocro`, of which this is just one.  I don't want have to bump the version number each time one of these documentation pages changes.  I started with this one because I just had to go through these steps, so that they were fresh in my mind.  But I don't see this as an urgent critical fix.  Most general users, in fact, will never look at this page.

**Comment by gsrohde** [comment]
> All of our branches are the same at this point, so it doesn't particularly matter but I am wondering why this wouldn't be treated as a hotfix and merged with main and develop simultaneously. I think of a hotfix as something that you want done everywhere, immediately. Doesn't this change pertain to both main and develop?

I didn't think this was urgent enough to be a hotfix.  See [my previous comment](https://github.com/biocro/biocro/pull/37#issuecomment-1791147601).

**Comment by justinmcgrath** [comment]
> This is the way Markdown handles numbered lists. It spares one having to renumber everything if you add a new item in the middle. They will be numbered correctly when they appear in the **bookdown** book.

It does render them properly, but one of the points of Markdown is that is that it is formatted nicely in the source in addition to any way it's rendered.

**Comment by gsrohde** [comment]
> It does render them properly, but one of the points of Markdown is that is that it is formatted nicely in the source in addition to any way it's rendered.

OK, I've renumbered the items sequentially.

**Review by justinmcgrath — APPROVED** [review]

**Pull request merged**
